"""
This script tests get_OH_dipoles_ir for a simple, synthetic case.

Input files: in ./fixtures/ :
  in.yaml : input file to invoke get_OH_dipoles_ir
  OH_dipoles.dat : synthetic O-H bond vectors for two H atoms
      (index 700, 682), each oscillating at one known wavenumber
      (3600 cm^-1 and 3800 cm^-1 respectively, well separated and
      well within the Nyquist limit for dt_fs = 0.5) and with a
      different oscillation amplitude (H 700: 0.08 Ang, H 682:
      0.04 Ang), generated by fixtures/generate_OH_dipoles.py,
      analogous to two synthetic normal modes of different strength.
  OH_freq_hand.dat : expected intensity-weighted OH frequencies and
      standard deviations for the synthetic vectors.

We check that get_OH_dipoles_ir recovers, for each H index, a partial
IR spectrum whose peak is close to the wavenumber that was used to
generate its synthetic O-H vector, and that the two partial spectra are
correctly kept separate (peaks are not swapped). We also check that,
by default (OH_normalize not set / False), the two partial spectra are
NOT independently rescaled -- so H 700 (larger amplitude) comes out with
a taller peak than H 682 (smaller amplitude) -- and that setting
OH_normalize: True instead forces both peaks to 1, matching ir.py's own
(single-spectrum) convention.
"""
import os
import unittest
import numpy as np
import yaml
from thermo_SiO2.IR_spectrum.dipole.get_OH_dipoles_ir import (
    compute_OH_frequency_statistics,
    fit_global_frequency_regression,
    get_OH_dipoles_ir,
    load_OH_dipoles,
    load_OH_frequency_metadata,
    load_OH_types,
    plot_OH_frequency_vs_bond_length,
    read_OH_dipole_H_indices,
    select_H_indices,
    sum_ir_by_OH_type,
)
from thermo_SiO2.IR_spectrum.dipole.ir import (
    compute_ir_from_dipole_components,
)

EXPECTED_WAVENUMBER = {700: 3600.0, 682: 3800.0}
OUTPUT_DATA = 'test_output_IR_spectrum_OH.dat'
OUTPUT_PLOT = 'test_output_IR_spectrum_OH.pdf'
OUTPUT_GROUP_PLOT = 'test_output_IR_spectrum_OH_group.pdf'
OUTPUT_GROUP_DATA = 'test_output_IR_spectrum_OH_group.dat'
OUTPUT_FREQ_PLOT = 'test_output_OH_freq_vs_bond_length.pdf'
OUTPUT_FREQ_DATA = 'test_output_OH_freq.dat'
TEMP_ANALYSIS = 'test_OH_analysis.csv'
TEMP_REGRESSION_PLOT = 'test_OH_regression.pdf'
GROUP_DATA_HAND = 'fixtures/IR_spectrum_OH_group_hand.dat'
FREQ_DATA_HAND = 'fixtures/OH_freq_hand.dat'
NORMALIZED_IN_FILE = 'fixtures/in_normalize.yaml'
ALL_H_IN_FILE = 'fixtures/in_all_H.yaml'


class TestGetOHDipolesIR(unittest.TestCase):

    def setUp(self):
        # a second in.yaml, identical to fixtures/in.yaml but with
        # OH_normalize: True, to test the opt-in normalized behavior
        with open('fixtures/in.yaml') as f:
            param = yaml.safe_load(f)
        param['OH_normalize'] = True
        with open(NORMALIZED_IN_FILE, 'w') as f:
            yaml.safe_dump(param, f)

        param.pop('OH_normalize')
        param.pop('OH_dipole_H_indices')
        param['OH_dipole_H_all'] = True
        with open(ALL_H_IN_FILE, 'w') as f:
            yaml.safe_dump(param, f)

    def tearDown(self):
        # get_OH_dipoles_ir writes these (per fixtures/in.yaml); clean up
        # so nothing test-generated is left lying around in the repo.
        for f in (
            OUTPUT_DATA, OUTPUT_PLOT, OUTPUT_GROUP_PLOT, OUTPUT_GROUP_DATA,
            OUTPUT_FREQ_PLOT, OUTPUT_FREQ_DATA, TEMP_ANALYSIS,
            TEMP_REGRESSION_PLOT,
            NORMALIZED_IN_FILE, ALL_H_IN_FILE,
        ):
            if os.path.exists(f):
                os.remove(f)

    def test_get_OH_dipoles_ir_not_normalized_by_default(self):
        print('\ntest_get_OH_dipoles_ir_not_normalized_by_default')
        freq_cm, ir_by_H = get_OH_dipoles_ir('fixtures/in.yaml')

        self.assertEqual(set(ir_by_H.keys()), set(EXPECTED_WAVENUMBER.keys()))

        peaks = {}
        for h_idx, wn_expected in EXPECTED_WAVENUMBER.items():
            ir = ir_by_H[h_idx]
            self.assertEqual(len(ir), len(freq_cm))

            peak_wn = freq_cm[np.argmax(ir)]
            peaks[h_idx] = np.max(ir)
            print(f'H {h_idx}: peak at {peak_wn:.1f} cm^-1 '
                  f'(expected ~{wn_expected} cm^-1), height {peaks[h_idx]:.4g}')
            # cut_autocorr = 500 fs -> frequency resolution is fairly
            # coarse; allow some tolerance.
            self.assertAlmostEqual(peak_wn, wn_expected, delta=100)

        # Not normalized: peak heights should differ between the two H
        # atoms, reflecting H 700's larger synthetic oscillation
        # amplitude (0.08 Ang) vs. H 682's smaller one (0.04 Ang) --
        # i.e. they must NOT both come out at 1.
        self.assertGreater(peaks[700], peaks[682])
        self.assertFalse(np.isclose(peaks[700], 1.0))
        self.assertFalse(np.isclose(peaks[682], 1.0))

        # saved data file: 1 frequency column + 1 intensity column per H
        saved = np.loadtxt(OUTPUT_DATA)
        self.assertEqual(saved.shape[1], 1 + len(EXPECTED_WAVENUMBER))
        # rtol only: values were written with fmt='%.6g', so exact
        # equality is not expected.
        np.testing.assert_allclose(saved[:, 0], freq_cm, rtol=1e-5)
        self.assertTrue(os.path.exists(OUTPUT_GROUP_PLOT))
        self.assertTrue(os.path.exists(OUTPUT_FREQ_PLOT))
        with open(OUTPUT_FREQ_DATA) as f:
            actual_frequency_header = f.readline()
        with open(FREQ_DATA_HAND) as f:
            expected_frequency_header = f.readline()
        self.assertEqual(actual_frequency_header, expected_frequency_header)
        np.testing.assert_allclose(
            np.loadtxt(OUTPUT_FREQ_DATA),
            np.loadtxt(FREQ_DATA_HAND),
            rtol=1e-5,
            atol=1e-6,
        )

        with open(OUTPUT_GROUP_DATA) as f:
            actual_header = f.readline()
        with open(GROUP_DATA_HAND) as f:
            expected_header = f.readline()
        self.assertEqual(actual_header, expected_header)
        np.testing.assert_allclose(
            np.loadtxt(OUTPUT_GROUP_DATA),
            np.loadtxt(GROUP_DATA_HAND),
            rtol=1e-5,
            atol=1e-12,
        )

    def test_get_OH_dipoles_ir_normalize_true(self):
        print('\ntest_get_OH_dipoles_ir_normalize_true')
        freq_cm, ir_by_H = get_OH_dipoles_ir(NORMALIZED_IN_FILE)
        for h_idx in EXPECTED_WAVENUMBER:
            self.assertAlmostEqual(np.max(ir_by_H[h_idx]), 1.0, places=6)

    def test_get_OH_dipoles_ir_all_H(self):
        freq_cm, ir_by_H = get_OH_dipoles_ir(ALL_H_IN_FILE)
        self.assertGreater(len(freq_cm), 0)
        self.assertEqual(list(ir_by_H), [700, 682])

    def test_select_H_indices(self):
        dipoles_file = 'fixtures/OH_dipoles.dat'
        self.assertEqual(
            read_OH_dipole_H_indices(dipoles_file), [700, 682]
        )
        self.assertEqual(
            select_H_indices({'OH_dipole_H_all': True}, dipoles_file),
            [700, 682],
        )
        self.assertEqual(
            select_H_indices(
                {'OH_dipole_H_indices': [682]}, dipoles_file
            ),
            [700, 682],
        )
        with self.assertRaisesRegex(ValueError, 'not both'):
            select_H_indices(
                {
                    'OH_dipole_H_indices': [700, 682],
                    'OH_dipole_H_all': True,
                },
                dipoles_file,
            )

    def test_sum_ir_by_OH_type(self):
        ir_by_H = {
            1: np.array([1.0, 2.0, 3.0]),
            2: np.array([0.5, 1.0, 1.5]),
            3: np.array([4.0, 5.0, 6.0]),
        }
        OH_types_by_H = {1: 'Si-OH', 2: 'Si-OH', 3: 'Al-OH'}
        grouped = sum_ir_by_OH_type(ir_by_H, OH_types_by_H)

        self.assertEqual(list(grouped), ['Si-OH', 'Al-OH'])
        np.testing.assert_allclose(grouped['Si-OH'], [1.5, 3.0, 4.5])
        np.testing.assert_allclose(grouped['Al-OH'], [4.0, 5.0, 6.0])

        loaded = load_OH_types(
            'fixtures/OH_analysis.csv', [700, 682]
        )
        self.assertEqual(loaded, {700: 'Si-OH', 682: 'Al-OH'})

    def test_compute_OH_frequency_statistics(self):
        freq_cm = np.array([1000.0, 2000.0, 3000.0, 4000.0])
        ir_by_H = {7: np.array([100.0, 100.0, 1.0, 3.0])}

        stats = compute_OH_frequency_statistics(freq_cm, ir_by_H)

        mean, stdev = stats[7]
        self.assertAlmostEqual(mean, 3750.0)
        self.assertAlmostEqual(stdev, np.sqrt(187500.0))
        with self.assertRaisesRegex(ValueError, 'zero total weight'):
            compute_OH_frequency_statistics(
                freq_cm, {7: np.zeros_like(freq_cm)}
            )

    def test_global_frequency_regression(self):
        slope, intercept, r_squared = fit_global_frequency_regression(
            [0.95, 1.00, 1.05], [3800.0, 3600.0, 3400.0]
        )
        self.assertAlmostEqual(slope, -4000.0)
        self.assertAlmostEqual(intercept, 7600.0)
        self.assertAlmostEqual(r_squared, 1.0)

        with self.assertRaisesRegex(ValueError, 'distinct OH bond lengths'):
            fit_global_frequency_regression([1.0, 1.0], [3600.0, 3700.0])

    def test_load_OH_frequency_metadata(self):
        with open(TEMP_ANALYSIS, 'w') as f:
            f.write(
                'H_index,OH_type,OH_bond_length,Hbond_O_indices\n'
                '1,Si-OH,0.98,[]\n'
                '2,Al-OH,1.02,"[15, 19]"\n'
            )

        metadata = load_OH_frequency_metadata(TEMP_ANALYSIS, [2, 1])

        self.assertEqual(metadata['H_index'].tolist(), [2, 1])
        self.assertEqual(
            metadata['Hbond_status'].tolist(), ['H-bonded', 'free']
        )
        np.testing.assert_allclose(
            metadata['OH_bond_length'], [1.02, 0.98]
        )
        plot_OH_frequency_vs_bond_length(
            TEMP_REGRESSION_PLOT,
            {2: (3400.0, 50.0), 1: (3700.0, 40.0)},
            metadata,
        )
        self.assertTrue(os.path.exists(TEMP_REGRESSION_PLOT))

    def test_group_dipole_preserves_mode_intensity_cross_terms(self):
        dt_fs = 0.5
        time_fs = np.arange(8000) * dt_fs
        phase_factor = 2.0 * np.pi * 2.99793e-5
        stretch = np.sin(phase_factor * 3300.0 * time_fs)
        antistretch = np.sin(phase_factor * 4100.0 * time_fs)

        mu_1 = 0.05 * stretch + 0.05 * antistretch
        mu_2 = 0.05 * stretch - 0.05 * antistretch
        zeros = np.zeros_like(mu_1)

        freq_cm, grouped_ir = compute_ir_from_dipole_components(
            [mu_1 + mu_2, zeros, zeros],
            dt_fs,
            cut_autocorr=500,
            normalize=False,
        )
        _, ir_1 = compute_ir_from_dipole_components(
            [mu_1, zeros, zeros],
            dt_fs,
            cut_autocorr=500,
            normalize=False,
        )
        _, ir_2 = compute_ir_from_dipole_components(
            [mu_2, zeros, zeros],
            dt_fs,
            cut_autocorr=500,
            normalize=False,
        )
        independent_sum = ir_1 + ir_2

        def peak_near(intensity, center):
            mask = np.abs(freq_cm - center) < 100.0
            return np.max(intensity[mask])

        grouped_stretch = peak_near(grouped_ir, 3300.0)
        grouped_antistretch = peak_near(grouped_ir, 4100.0)
        independent_antistretch = peak_near(independent_sum, 4100.0)

        self.assertGreater(grouped_stretch, 100.0 * grouped_antistretch)
        self.assertLess(
            grouped_antistretch, 0.05 * independent_antistretch
        )


    def test_load_OH_dipoles(self):
        print('\ntest_load_OH_dipoles')
        oh_dipoles = load_OH_dipoles('fixtures/OH_dipoles.dat', [700, 682])
        self.assertEqual(set(oh_dipoles.keys()), {700, 682})
        for h_idx in (700, 682):
            self.assertEqual(oh_dipoles[h_idx].shape[1], 3)

        with self.assertRaises(ValueError):
            # wrong number of H indices for the data file
            load_OH_dipoles('fixtures/OH_dipoles.dat', [700, 682, 1])


if __name__ == '__main__':
    unittest.main()
