#!/usr/bin/env python3
"""This module provides a function for reading mlip cfg files."""
import sys
import numpy as np
import ase
from ase.io import write
from mlippy.atms import ase_loadcfgs
from ..util.SiO2_parameter import (atomic_symbol_to_number,
        atomic_number_to_POTCAR_order)


# VERBOSE = True  # debug
VERBOSE = False

def read_mlip_cfg(filename, atom_symbol_tuple={0: 'X'},
        sort_method=False):
    """ This function reads a *.cfgs file generated by mlip program
    and returns a tuple of ase atoms object and forces.
    returned object: atoms_and_forces[0]['atoms'] and atoms_and_forces[0]['forces'],
    [1], ...
    atom_symbol_tuple: ex) {0: 'Al'}. When atom types are written, the type
    should start from 0.
    This script is not general and the lines should be modified according to the
    written keys."""
    atoms_and_forces = []
    with open(filename, 'rt') as infile:  # t: text mode
        last_pos = infile.tell()
        first_line = infile.readline() # BEGIN_CFG
        if 'BEGIN_CFG' not in first_line:
            print('Error: This file is probably not cfg file by mlip.')
            sys.exit()
        infile.seek(last_pos)
        first_line = infile.readline()  # BEGIN_CFG

        while first_line != "":
            # first_line = infile.readline()  # BEGIN_CFG
            # print('first_line =',first_line) ##
            infile.readline()  # Size
            # print(infile.readline())  # Size ##
            # breakpoint()
            num_atoms = int(infile.readline().split()[0])  # ex) 108

            infile.readline()  # Supercell
            vec_a = np.array(infile.readline().split(), dtype=float)
            vec_b = np.array(infile.readline().split(), dtype=float)
            vec_c = np.array(infile.readline().split(), dtype=float)
            if VERBOSE:
                print('num_atoms =', num_atoms)
                print('vec_a=', vec_a)
                print('vec_b=', vec_b)
                print('vec_c=', vec_c)

            infile.readline()
            # AtomData:  id type       cartes_x      cartes_y      cartes_z
            #   fx          fy          fz
            types = []
            positions = []
            forces = []
            for num_lines in range(num_atoms):
                atom_data = np.array(infile.readline().split(), dtype=float)
                types.append(atom_symbol_tuple[atom_data[1]])
                positions.append(atom_data[2:5])
                forces.append(atom_data[5:8])
            if VERBOSE:
                print('types =', types)
                print('positions =', positions)
                print('forces =', forces)
            if infile.readline().split()[0] == 'Energy':
                energy = float(infile.readline().split()[0])
                if VERBOSE:
                    print('energy =', energy)
            if infile.readline().split()[0] == 'PlusStress':
                # infile.readline()  # PlusStress:  xx          yy          zz
                #          yz          xz          xy
                stress = np.array(infile.readline().split(), dtype=float)
            # myCalculator = infile.readline().split()[2]   # MultiMPT30
            # myConfigNumber = int(infile.readline().split()[2])

            # if infile.readline().split()[0] == 'Feature':
            #     infile.readline()  # END_CFG
            # infile.readline()  # blank
            MAX_FEATURE_LINE = 10
            for index_line in range(MAX_FEATURE_LINE):
                line = infile.readline()
                if line.split()[0] == 'Feature':
                    continue
                elif line.split()[0] == 'END_CFG':
                    break
            infile.readline()  # blank

            atom_symbol_joined = ''.join(types)

            positions = np.array(positions)
            config = ase.Atoms(atom_symbol_joined, cell=[vec_a, vec_b, vec_c],
                               positions=positions, pbc=True)

            if VERBOSE:
                print('config =', config)
                print('config[0] =', config[0])
                print('atom_symbol_joined=', atom_symbol_joined)
                print(f'{config.get_chemical_symbols() =}')

            forces = np.array(forces)
            if sort_method == 'True':
                sort_index = np.argsort(config.get_atomic_numbers())
                config = config[sort_index]
                forces = forces[sort_index]
            elif sort_method == 'POTCAR_order':
                # atomic_numbers = config.get_atomic_numbers()
                number_to_sort = [atomic_number_to_POTCAR_order[atomic_number]
                        for atomic_number in config.get_atomic_numbers()]
                # number_to_sort = np.zeroes(len(atomic_numbers))
                # for index, atomic_number in enumerate(atomic_numbers):
                #     number_to_sort[index] = atomic_number_to_POTCAR_order[atomic_number]
                sort_index = np.argsort(number_to_sort)
                config = config[sort_index]
                forces = forces[sort_index]
            atoms_and_forces.append({'atoms': config, 'forces': forces})
            first_line = infile.readline()  # BEGIN_CFG

        if VERBOSE:
            print('atoms_and_forces =', atoms_and_forces)
            # write('positions.traj', atoms_and_forces[:]['atoms'])
            # write('positions.extxyz', atoms_and_forces[0]['atoms'])
    
        # if write_extxyz:
        #     atoms_list = []
        #     for config in atoms_and_forces:
        #         atoms_list.append(config['atoms'])
        #     write('positions.extxyz', atoms_list)

    return atoms_and_forces


def read_mlip_cfg_positions(filename, atom_symbol_tuple={0: 'X'}):
        # write_extxyz=False):
    """This function reads positions of mlip cfgs and returns a list of atoms
    objects."""
    atoms_and_forces_list = read_mlip_cfg(filename,
            # atom_symbol_tuple=atom_symbol_tuple, write_extxyz=write_extxyz)
            atom_symbol_tuple=atom_symbol_tuple)
    atoms_list = []
    for atoms_and_forces in atoms_and_forces_list:
        atoms_list.append(atoms_and_forces['atoms'])
    return atoms_list


def set_atom_symbol(configs, atom_symbol_tuple):
    """This function changes atom atom type (0, 1, 2, .., or 1, 2, 3, ...) to 
    symbols using atom_symbol_tuple."""
    if type(configs).__name__ == 'Atoms':
        configs = [configs]
        # If there is one configuration, convert it to a list of configs.
    for config in configs:
        atomic_numbers = config.get_atomic_numbers()
        # print(f'{atomic_numbers =}')  # [0 0 0 0 0 0 1  ...
        real_numbers = np.zeros(len(atomic_numbers))  # actual numbers
        # symbols = np.chararray((len(config)), itemsize=8)
        # eight enough letters for chemical symbols
        for index, atomic_number in enumerate(atomic_numbers):
            real_numbers[index] = atomic_symbol_to_number[ atom_symbol_tuple[
                atomic_number]]
        config.set_atomic_numbers(real_numbers)
    if len(configs) == 1:
        configs = configs[0]
        # convert list of configs to one config.
        




# if __name__ == '__main__':
# # Test
#     # read_mlip_cfg('config_mlip.cfgs', atom_symbol_tuple={0: 'Al'})
#     atoms_and_forces = read_mlip_cfg('config_mlip.cfgs', atom_symbol_tuple={0: 'Al'}, write_extxyz=True)
#     # print(read_mlip_cfg('config_mlip.cfgs', atom_symbol_tuple={0: 'Al'}))
