# Boilerplate code generated by OVITO Pro 3.14.1
import numpy as np
import argparse
from ovito.io import *
from ovito.io.ase import ovito_to_ase
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *

def get_num_H_s(pipeline):
    data = pipeline.compute()
    # num_H_s = np.count_nonzero(data.particles['ParticleType'] == 3)
    ase_atoms = ovito_to_ase(data)
    num_H_s = np.count_nonzero(np.array(ase_atoms.get_chemical_symbols()) == 'H')
    return num_H_s

def remove_unbound_atoms(file_in, file_out):

    # ==== Set up pipeline ==== #

    # Data import:
    # pipeline = import_file(file_in, multiple_frames = True)
    pipeline = import_file(file_in)
    # User-defined modifier function 'Python script':
    from ovito.data import DataCollection
    from ovito.pipeline import ModifierInterface
    from traits.api import Str

        
    def modify(frame: int, data: DataCollection):
        # pass
            
        # This user-defined modifier function gets automatically called by OVITO whenever the data pipeline is newly computed.
        # It receives two arguments from the pipeline system:
        # 
        #    frame - The current animation frame number at which the pipeline is being evaluated.
        #    data  - The DataCollection passed in from the pipeline system. 
        #            The function may modify the data stored in this DataCollection as needed.
        # 
        # What follows is an example code snippet doing nothing aside from printing the current 
        # list of particle properties to the log window. Use it as a starting point for developing 
        # your own data modification or analysis functions. 
            
        # if data.particles != None:
        #     print("There are %i particles with the following properties:" % data.particles.count)
            #     for property_name in data.particles.keys():
            #         print("  '%s'" % property_name)
            #     data.particles_.particle_types_.type_by_id_(1).color = [0.9411764740943909, 0.7843137383460999, 0.6274510025978088]
            #symbols = Str('Si O H Al', label='Symbols')

            # # atom type: Si O
            # symbols = self.symbols
        symbols = 'Si O H Al'
        data.particles_.particle_types_.type_by_id_(1).color = [0.9411764740943909, 0.7843137383460999, 0.6274510025978088]
        data.particles_.particle_types_.type_by_id_(1).name = 'Si'
        data.particles_.particle_types_.type_by_id_(1).radius = 1.18
        data.particles_.particle_types_.type_by_id_(1).vdw_radius = 2.1

        data.particles_.particle_types_.type_by_id_(2).color = [1.0, 0.05098039284348488, 0.05098039284348488]
        data.particles_.particle_types_.type_by_id_(2).name = 'O'
        data.particles_.particle_types_.type_by_id_(2).radius = 0.74
        data.particles_.particle_types_.type_by_id_(2).vdw_radius = 1.52

        if symbols == 'Si O Al':        
            data.particles_.particle_types_.type_by_id_(3).color = [0.7490196228027344, 0.6509804129600525, 0.6509804129600525]
            data.particles_.particle_types_.type_by_id_(3).name = 'Al'
            data.particles_.particle_types_.type_by_id_(3).radius = 1.43
            data.particles_.particle_types_.type_by_id_(3).vdw_radius = 2.0

        elif symbols == 'Si O H Al':
            data.particles_.particle_types_.type_by_id_(3).color = [1, 1, 1]
            data.particles_.particle_types_.type_by_id_(3).name = 'H'
            data.particles_.particle_types_.type_by_id_(3).radius = 0.46
            data.particles_.particle_types_.type_by_id_(3).vdw_radius = 1.2

            data.particles_.particle_types_.type_by_id_(4).color = [0.7490196228027344, 0.6509804129600525, 0.6509804129600525]
            data.particles_.particle_types_.type_by_id_(4).name = 'Al'
            data.particles_.particle_types_.type_by_id_(4).radius = 1.43
            data.particles_.particle_types_.type_by_id_(4).vdw_radius = 2.0
            
        else:
            print('Unsupported symbols')

        # print(f'Atom types: {symbols}')


    pipeline.modifiers.append(modify)

    # Create bonds:
    mod = CreateBondsModifier()
    mod.mode = CreateBondsModifier.Mode.Pairwise
    mod.set_pairwise_cutoff('Al', 'Al', 2.4)
    mod.set_pairwise_cutoff('H', 'Al', 1.92)
    mod.set_pairwise_cutoff('O', 'Al', 2.112)
    mod.set_pairwise_cutoff('O', 'H', 1.55)  # not too long
    mod.set_pairwise_cutoff('O', 'O', 1.8239999999999998)
    mod.set_pairwise_cutoff('Si', 'Al', 2.4599999999999995)
    mod.set_pairwise_cutoff('Si', 'H', 1.9799999999999998)
    mod.set_pairwise_cutoff('Si', 'O', 2.172)
    mod.set_pairwise_cutoff('Si', 'Si', 2.52)
    pipeline.modifiers.append(mod)

    # Skipping modifier 'Manual selection'
    # Expression selection:
    data = pipeline.compute()
    ase_atoms = ovito_to_ase(data)
    print(f'First atoms: {ase_atoms.get_chemical_formula()}')

    num_H_s = get_num_H_s(pipeline)
    print(f"first H's: {num_H_s}")
    # breakpoint()

    pipeline.modifiers.append(ExpressionSelectionModifier(
        expression = '1', 
        enabled = False))

    # Cluster analysis:
    pipeline.modifiers.append(ClusterAnalysisModifier(
        neighbor_mode = ClusterAnalysisModifier.NeighborMode.Bonding, 
        sort_by_size = True, 
        unwrap_particles = True, 
        compute_gyration = True))

    # Expression selection:
    pipeline.modifiers.append(ExpressionSelectionModifier(expression = 'Cluster!=1'))
    # The largest cluster is 1.
    data = pipeline.compute()
    print(f"Particles removed: {data.attributes['ExpressionSelection.count']}")

    # Delete selected:
    pipeline.modifiers.append(DeleteSelectedModifier())

    # # Expression selection:
    # pipeline.modifiers.append(ExpressionSelectionModifier(
    #     expression = 'ParticleType==3', 
    #     enabled = False))
    # data = pipeline.compute()
    num_H_s = get_num_H_s(pipeline)
    print(f"H's remained: {num_H_s}")

    data = pipeline.compute()
    ase_atoms = ovito_to_ase(data)
    print(f'Remaining atoms: {ase_atoms.get_chemical_formula()}')

    # Assign color:
    # pipeline.modifiers.append(AssignColorModifier(
    #     color = [0.0, 0.0, 1.0], 
    #     enabled = False))
    export_file(pipeline, file_out, 'lammps/data', 
        ignore_identifiers=True)



def main():
    parser = argparse.ArgumentParser(description='Remove unbound atoms from a structure file.')
    parser.add_argument('input_file', type=str, help='Path to the input structure file.')
    parser.add_argument('output_file', type=str, help='Path to the output structure file.')
    args = parser.parse_args()

    remove_unbound_atoms(args.input_file, args.output_file)

if __name__ == "__main__":
    main()