"""
This script tests get_OH_vectors_ir for a simple, synthetic case.

Input files: in ./fixtures/ :
  in.yaml : input file to invoke get_OH_vectors_ir
  OH_vectors.dat : synthetic O-H bond vectors for two H atoms
      (index 700, 682), each oscillating at one known wavenumber
      (3600 cm^-1 and 2600 cm^-1 respectively, well separated and
      well within the Nyquist limit for dt_fs = 0.5) and with a
      different oscillation amplitude (H 700: 0.08 Ang, H 682:
      0.04 Ang), generated by a small script (see git history),
      analogous to two synthetic normal modes of different strength.

We check that get_OH_vectors_ir recovers, for each H index, a partial
IR spectrum whose peak is close to the wavenumber that was used to
generate its synthetic O-H vector, and that the two partial spectra are
correctly kept separate (peaks are not swapped). We also check that,
by default (OH_normalize not set / False), the two partial spectra are
NOT independently rescaled -- so H 700 (larger amplitude) comes out with
a taller peak than H 682 (smaller amplitude) -- and that setting
OH_normalize: True instead forces both peaks to 1, matching ir.py's own
(single-spectrum) convention.
"""
import os
import unittest
import numpy as np
import yaml
from thermo_SiO2.IR_spectrum.dipole.get_OH_vectors_ir import (
    get_OH_vectors_ir,
    load_OH_vectors,
    load_OH_types,
    read_OH_vector_H_indices,
    select_H_indices,
    sum_ir_by_OH_type,
)

EXPECTED_WAVENUMBER = {700: 3600.0, 682: 2600.0}
OUTPUT_DATA = 'test_output_IR_spectrum_OH.dat'
OUTPUT_PLOT = 'test_output_IR_spectrum_OH.pdf'
OUTPUT_GROUP_PLOT = 'test_output_IR_spectrum_OH_group.pdf'
OUTPUT_GROUP_DATA = 'test_output_IR_spectrum_OH_group.dat'
GROUP_DATA_HAND = 'fixtures/IR_spectrum_OH_group_hand.dat'
NORMALIZED_IN_FILE = 'fixtures/in_normalize.yaml'
ALL_H_IN_FILE = 'fixtures/in_all_H.yaml'


class TestGetOHVectorsIR(unittest.TestCase):

    def setUp(self):
        # a second in.yaml, identical to fixtures/in.yaml but with
        # OH_normalize: True, to test the opt-in normalized behavior
        with open('fixtures/in.yaml') as f:
            param = yaml.safe_load(f)
        param['OH_normalize'] = True
        with open(NORMALIZED_IN_FILE, 'w') as f:
            yaml.safe_dump(param, f)

        param.pop('OH_normalize')
        param.pop('OH_vector_H_indices')
        param['OH_vector_H_all'] = True
        with open(ALL_H_IN_FILE, 'w') as f:
            yaml.safe_dump(param, f)

    def tearDown(self):
        # get_OH_vectors_ir writes these (per fixtures/in.yaml); clean up
        # so nothing test-generated is left lying around in the repo.
        for f in (
            OUTPUT_DATA, OUTPUT_PLOT, OUTPUT_GROUP_PLOT, OUTPUT_GROUP_DATA,
            NORMALIZED_IN_FILE, ALL_H_IN_FILE,
        ):
            if os.path.exists(f):
                os.remove(f)

    def test_get_OH_vectors_ir_not_normalized_by_default(self):
        print('\ntest_get_OH_vectors_ir_not_normalized_by_default')
        freq_cm, ir_by_H = get_OH_vectors_ir('fixtures/in.yaml')

        self.assertEqual(set(ir_by_H.keys()), set(EXPECTED_WAVENUMBER.keys()))

        peaks = {}
        for h_idx, wn_expected in EXPECTED_WAVENUMBER.items():
            ir = ir_by_H[h_idx]
            self.assertEqual(len(ir), len(freq_cm))

            peak_wn = freq_cm[np.argmax(ir)]
            peaks[h_idx] = np.max(ir)
            print(f'H {h_idx}: peak at {peak_wn:.1f} cm^-1 '
                  f'(expected ~{wn_expected} cm^-1), height {peaks[h_idx]:.4g}')
            # cut_autocorr = 500 fs -> frequency resolution is fairly
            # coarse; allow some tolerance.
            self.assertAlmostEqual(peak_wn, wn_expected, delta=100)

        # Not normalized: peak heights should differ between the two H
        # atoms, reflecting H 700's larger synthetic oscillation
        # amplitude (0.08 Ang) vs. H 682's smaller one (0.04 Ang) --
        # i.e. they must NOT both come out at 1.
        self.assertGreater(peaks[700], peaks[682])
        self.assertFalse(np.isclose(peaks[700], 1.0))
        self.assertFalse(np.isclose(peaks[682], 1.0))

        # saved data file: 1 frequency column + 1 intensity column per H
        saved = np.loadtxt(OUTPUT_DATA)
        self.assertEqual(saved.shape[1], 1 + len(EXPECTED_WAVENUMBER))
        # rtol only: values were written with fmt='%.6g', so exact
        # equality is not expected.
        np.testing.assert_allclose(saved[:, 0], freq_cm, rtol=1e-5)
        self.assertTrue(os.path.exists(OUTPUT_GROUP_PLOT))

        with open(OUTPUT_GROUP_DATA) as f:
            actual_header = f.readline()
        with open(GROUP_DATA_HAND) as f:
            expected_header = f.readline()
        self.assertEqual(actual_header, expected_header)
        np.testing.assert_allclose(
            np.loadtxt(OUTPUT_GROUP_DATA),
            np.loadtxt(GROUP_DATA_HAND),
            rtol=1e-5,
            atol=1e-12,
        )

    def test_get_OH_vectors_ir_normalize_true(self):
        print('\ntest_get_OH_vectors_ir_normalize_true')
        freq_cm, ir_by_H = get_OH_vectors_ir(NORMALIZED_IN_FILE)
        for h_idx in EXPECTED_WAVENUMBER:
            self.assertAlmostEqual(np.max(ir_by_H[h_idx]), 1.0, places=6)

    def test_get_OH_vectors_ir_all_H(self):
        freq_cm, ir_by_H = get_OH_vectors_ir(ALL_H_IN_FILE)
        self.assertGreater(len(freq_cm), 0)
        self.assertEqual(list(ir_by_H), [700, 682])

    def test_select_H_indices(self):
        vectors_file = 'fixtures/OH_vectors.dat'
        self.assertEqual(
            read_OH_vector_H_indices(vectors_file), [700, 682]
        )
        self.assertEqual(
            select_H_indices({'OH_vector_H_all': True}, vectors_file),
            [700, 682],
        )
        self.assertEqual(
            select_H_indices(
                {'OH_vector_H_indices': [682]}, vectors_file
            ),
            [682],
        )
        with self.assertRaisesRegex(ValueError, 'not both'):
            select_H_indices(
                {
                    'OH_vector_H_indices': [700, 682],
                    'OH_vector_H_all': True,
                },
                vectors_file,
            )

    def test_sum_ir_by_OH_type(self):
        ir_by_H = {
            1: np.array([1.0, 2.0, 3.0]),
            2: np.array([0.5, 1.0, 1.5]),
            3: np.array([4.0, 5.0, 6.0]),
        }
        OH_types_by_H = {1: 'Si-OH', 2: 'Si-OH', 3: 'Al-OH'}
        grouped = sum_ir_by_OH_type(ir_by_H, OH_types_by_H)

        self.assertEqual(list(grouped), ['Si-OH', 'Al-OH'])
        np.testing.assert_allclose(grouped['Si-OH'], [1.5, 3.0, 4.5])
        np.testing.assert_allclose(grouped['Al-OH'], [4.0, 5.0, 6.0])

        loaded = load_OH_types(
            'fixtures/OH_analysis.dat', [700, 682]
        )
        self.assertEqual(loaded, {700: 'Si-OH', 682: 'Al-OH'})

    def test_load_OH_vectors(self):
        print('\ntest_load_OH_vectors')
        oh_vectors = load_OH_vectors('fixtures/OH_vectors.dat', [700, 682])
        self.assertEqual(set(oh_vectors.keys()), {700, 682})
        for h_idx in (700, 682):
            self.assertEqual(oh_vectors[h_idx].shape[1], 3)

        with self.assertRaises(ValueError):
            # wrong number of H indices for the data file
            load_OH_vectors('fixtures/OH_vectors.dat', [700, 682, 1])


if __name__ == '__main__':
    unittest.main()
